name: tests

on:
  # Run this workflow every time a new commit is pushed to repo
  push:
  # Also run it once weekly to check for impact due to changes in the OS,
  # python, postgres, or any external packages/dependencies
  schedule:
  - cron: '7 14 * * fri'

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Test with specific supported versions
          - name: supported
            os: ubuntu-20.04
            python: 3.8
          # Test everything with latest versions
          - name: latest
            os: ubuntu-latest
            python: 3.x

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check for mypy typing issues
        run: mypy --strict extract.py
